### ISSUE TITLE
清除锯齿的貌似没效果

### ISSUE THREAD

**Issue by SplashZ** [ZhongTaoTian/Hardest#1]
非常感谢楼主的分享，让我大开眼见！
代码里发现有个除锯齿的方法，我试了下几乎没效果。
请问楼主，这个除锯齿的方法一般用在什么情况下才有效?

**Comment by ZhongTaoTian** [comment]
出现锯齿的原因是因为对UIImageView进行了旋转造成的,可以尝试设置imageIV.layer中偏移和边框,再裁减掉来解决
